### ISSUE TITLE
[CHORE] CI/CD 를 위한 세팅을 한다.

### ISSUE THREAD

**Issue by Jin409** [Indipage/SERVER#1]
## ✅ 구현할 기능
- CI/CD 를 위한 세팅을 완료한다.

## 📝 TODO
- [x] ci 를 위한 워크플로우 작성 및 테스트
- [ ] cd 를 위한 파이프라인 구축
- [ ] cd 를 위한 스크립트 작성
